# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a542bb32ba720f50bc846e6e890303bcb3c288b536620337965039c4d0e4389f03803e929f1f263dadb757de22d287b68d5de615e8dd45ba65359e44653b2fa

test:
  secret_key_base: e7945381d7d250e10cac1a1beaf5239db129ff9cb47e527c5969bc4d9327be907a859dc828ba8ed22a110bea40e7f861bdf88e8e704525c5234ab60388ffb20e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
